// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadEnvFile(arg1) {
  return window['go']['main']['App']['LoadEnvFile'](arg1);
}

export function SaveEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvFile'](arg1, arg2);
}
