// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddToHistory(arg1:string,arg2:string):Promise<void>;

export function GetHistory():Promise<Array<models.EnvHistory>>;

export function LoadEnvFile(arg1:string):Promise<Array<models.EnvVariable>>;

export function SaveEnvFile(arg1:string,arg2:Array<models.EnvVariable>):Promise<void>;
